monolog:
    channels: [
        'deprecation', # Deprecations are logged in the dedicated "deprecation" channel when it exists

        'api-tickets',
    ]

    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: [ '!event', '!doctrine', '!deprecation', '!console' ]
        deprecation:
            type: stream
            path: '%kernel.logs_dir%/deprecation.log'
            channels: [ 'deprecation' ]
        doctrine:
            type: stream
            path: '%kernel.logs_dir%/doctrine.log'
            channels: [ 'doctrine'  ]
        console:
            type: console
            process_psr_3_messages: false
            channels: [ '!event', '!doctrine', '!console' ]

        # CUSTOM
        api-tickets:
            type: stream
            path: '%kernel.logs_dir%/api-tickets.log'
            channels: [ api-tickets ]