version: "3.7"

services:
    php-api:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: php-api
        volumes:
            - ./:/var/www/html
            - ~/.ssh:/root/.ssh
        environment:
            APP_ENV: dev

    app-api:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: app-api
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - php-api
        environment:
            - APP_ENV=dev

    db-api:
        image: postgres:14.2
        container_name: db-api
        restart: always
        environment:
            POSTGRES_ROOT_PASSWORD: "secret"
            POSTGRES_DB: "airplane_tickets_api"
            POSTGRES_USER: "test"
            POSTGRES_PASSWORD: "secret"
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

networks:
    default:
        external:
            name: airplane_tickets

volumes:
    postgres_data:
        driver: "local"